    headers: Object [AxiosHeaders] {
      date: 'Tue, 31 Mar 2026 12:58:31 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '136',
      connection: 'close',
      'set-cookie': [Array],
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authorization: [Array],
      'user-agent': [Array],
      'content-length': [Array],
      server: 'Tengine',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      'access-control-allow-origin': '*',
      'access-control-allow-methods': 'DELETE,GET,OPTIONS,PATCH,POST,PUT',
      'access-control-allow-headers': 'authorization,content-length,content-type,user-agent,x-airtable-application-id,x-airtable-user-agent,x-api-version,x-requested-with',
      'x-frame-options': 'DENY',
      'x-content-type-options': 'nosniff',
      etag: 'W/"88-0RKdIPXOFcB4i3Mc83SGykWkzbI"',
      'airtable-datacenter-regions': 'us-east-1',
      vary: 'Accept-Encoding'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      method: 'post',
      url: 'https://api.airtable.com/v0/apprNLwet4uB8s6Ai/Owners',
      data: '{"fields":{"Name":"NammaHood","Phone":"+919380729579","Configuration":"2BHK, 3BHK","Location":"Clifton, close to HSR Hustlehub","Rental":25000,"OccupancyType":"Bachelor"}}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '171',
      _hasBody: true,
      _trailer: '',
        'Content-Length: 171\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: api.airtable.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/v0/apprNLwet4uB8s6Ai/Owners',
      _ended: true,
      res: [IncomingMessage],
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /v0/apprNLwet4uB8s6Ai/Owners HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Bearer patTBkxTK2zMYN355.66ab5c8c0867f465e578166bd0527a7f786b484c7a54faece03adc108535d5f5\r\n' +
        'User-Agent: axios/1.6.5\r\n' +
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.airtable.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { error: [Object] }
  }
}
